frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "public/**"
          - "app.css"
          - "fonts.css"
          - "tailwind.config.js"
          - "svelte.config.js"
          - "vite.config.ts"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/**"
          - "scripts/**/*.php"
          - "scripts/**/build-backend.*"
          - "config/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "README.md"
          - "backend/README.md"
          - "SECURITY.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/*.yml"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"
          - "playwright.config.ts"
          - "test-results/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "backend/composer.json"
          - "backend/composer.lock"
