-- Migration 005: Add stammtisch locations table
-- This migration adds the table for managing stammtisch locations on the map

CREATE TABLE IF NOT EXISTS stammtisch_locations (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  city VARCHAR(100) NOT NULL,
  region VARCHAR(100) NOT NULL,
  country VARCHAR(3) NOT NULL,
  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,
  description TEXT,
  contact_email VARCHAR(255),
  contact_phone VARCHAR(50),
  contact_telegram VARCHAR(100),
  contact_website VARCHAR(500),
  meeting_frequency VARCHAR(255),
  meeting_location VARCHAR(255),
  meeting_address TEXT,
  next_meeting DATETIME NULL,
  tags JSON,
  is_active BOOLEAN DEFAULT TRUE,
  status ENUM('draft', 'published', 'archived') DEFAULT 'draft',
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_country (country),
  INDEX idx_region (region),
  INDEX idx_city (city),
  INDEX idx_status (status),
  INDEX idx_is_active (is_active),
  INDEX idx_slug (slug),
  INDEX idx_coordinates (latitude, longitude),

  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert sample data for DACH region
INSERT INTO stammtisch_locations (
  id, name, slug, city, region, country, latitude, longitude,
  description, contact_email, contact_telegram, meeting_frequency,
  meeting_location, tags, is_active, status
) VALUES
(
  UUID(),
  'Hypnose Stammtisch Berlin',
  'hypnose-stammtisch-berlin',
  'Berlin',
  'Berlin',
  'DE',
  52.52000000,
  13.40500000,
  'Monatlicher Stammtisch für alle Interessierten der Hypnose in Berlin. Sowohl Anfänger als auch erfahrene Hypnotiseure sind willkommen.',
  'berlin@hypnose-stammtisch.de',
  '@HypnoseBerlin',
  'Jeden 1. Samstag im Monat',
  'Kulturzentrum Mitte, Seminarraum 3',
  JSON_ARRAY('anfängerfreundlich', 'praxis', 'theorie'),
  TRUE,
  'published'
),
(
  UUID(),
  'München Hypnose Circle',
  'muenchen-hypnose-circle',
  'München',
  'Bayern',
  'DE',
  48.13510000,
  11.58200000,
  'Praxisorientierte Treffen mit Fokus auf moderne Hypnosetechniken und Sicherheitspraktiken.',
  'muenchen@hypnose-stammtisch.de',
  NULL,
  'Jeden 3. Freitag im Monat',
  'Volkshochschule München, Raum 204',
  JSON_ARRAY('erfahren', 'praxis', 'sicherheit'),
  TRUE,
  'published'
),
(
  UUID(),
  'Hamburg Hypnose Treff',
  'hamburg-hypnose-treff',
  'Hamburg',
  'Hamburg',
  'DE',
  53.55110000,
  9.99370000,
  'Offene Runde für Hypnose-Enthusiasten im Norden. Wir praktizieren verschiedene Techniken und tauschen Erfahrungen aus.',
  'hamburg@hypnose-stammtisch.de',
  '@HypnoseHamburg',
  'Jeden 2. Donnerstag im Monat',
  'Bürgerzentrum Altona',
  JSON_ARRAY('gemischt', 'praxis', 'austausch'),
  TRUE,
  'published'
),
(
  UUID(),
  'Köln Hypnose Akademie',
  'koeln-hypnose-akademie',
  'Köln',
  'Nordrhein-Westfalen',
  'DE',
  50.93753000,
  6.96028000,
  'Akademischer Ansatz zur Hypnose mit wissenschaftlichen Diskussionen und strukturierten Übungen.',
  'koeln@hypnose-stammtisch.de',
  NULL,
  'Jeden 4. Mittwoch im Monat',
  'Universität Köln, Hörsaal 12',
  JSON_ARRAY('wissenschaftlich', 'theorie', 'fortgeschritten'),
  TRUE,
  'published'
),
(
  UUID(),
  'Hypnose Stammtisch Wien',
  'hypnose-stammtisch-wien',
  'Wien',
  'Wien',
  'AT',
  48.20849000,
  16.37208000,
  'Gemütliche Runde für Hypnose-Interessierte in Wien. Wir sprechen Deutsch und teilen unser Wissen gerne.',
  'wien@hypnose-stammtisch.de',
  '@HypnoseWien',
  'Jeden 1. Montag im Monat',
  'Volkshochschule Ottakring',
  JSON_ARRAY('gemütlich', 'austausch', 'anfängerfreundlich'),
  TRUE,
  'published'
),
(
  UUID(),
  'Zürich Hypnose Club',
  'zuerich-hypnose-club',
  'Zürich',
  'Zürich',
  'CH',
  47.37440000,
  8.54120000,
  'Exklusive Gruppe für erfahrene Praktiker. Fokus auf fortgeschrittene Techniken und professionelle Anwendung.',
  'zuerich@hypnose-stammtisch.de',
  NULL,
  'Jeden 2. Samstag im Monat',
  'Business Center Zürich',
  JSON_ARRAY('professionell', 'fortgeschritten', 'business'),
  TRUE,
  'published'
);
